### ISSUE TITLE
Random crashes in Azure DevOps build pipeline

### ISSUE THREAD

**Issue by Braini01** [Redth/ResizetizerNT#10] opened 2020-05-04 23:57 UTC
First of all: Very nice tool! Love it. 

But there seems to be an issue. I build my app in Azure DevOps with a CI pipeline and like 30-50% of the builds fail, because of native crashes. Below is the relevant excerpt of the log with the error. Since the error does not seem to be deterministic my guess would be that it is concurrency problem. Issue #8 might be related.

```
2020-05-04T23:42:49.9445030Z   Open SVG took 3ms
2020-05-04T23:42:49.9445420Z   new SKSvg() took 0ms
2020-05-04T23:42:49.9454110Z   svg.FromSvgDocument took 0ms
2020-05-04T23:42:49.9460130Z   Save Image took 0ms
2020-05-04T23:42:49.9470300Z   Save Image took 0ms
2020-05-04T23:42:49.9480840Z   Save Image took 0ms
2020-05-04T23:42:49.9490210Z   Save Image took 0ms
2020-05-04T23:42:49.9505890Z   Save Image took 1ms
2020-05-04T23:42:49.9883260Z 
2020-05-04T23:42:49.9883750Z =================================================================
2020-05-04T23:42:49.9884370Z 	Native Crash Reporting
2020-05-04T23:42:49.9884950Z =================================================================
2020-05-04T23:42:49.9885570Z Got a SIGSEGV while executing native code. This usually indicates
2020-05-04T23:42:49.9886640Z a fatal error in the mono runtime or one of the native libraries 
2020-05-04T23:42:49.9887070Z used by your application.
2020-05-04T23:42:49.9887370Z =================================================================
2020-05-04T23:42:49.9887610Z 
2020-05-04T23:42:49.9887850Z =================================================================
2020-05-04T23:42:49.9888150Z 	Native stacktrace:
2020-05-04T23:42:49.9888440Z =================================================================
2020-05-04T23:42:49.9889660Z 	0x1029bc1cb - /Library/Frameworks/Mono.framework/Versions/6.8.0/bin/mono : mono_dump_native_crash_info
2020-05-04T23:42:49.9890580Z 	0x1029547a5 - /Library/Frameworks/Mono.framework/Versions/6.8.0/bin/mono : mono_handle_native_crash
2020-05-04T23:42:49.9891490Z 	0x1029b62fe - /Library/Frameworks/Mono.framework/Versions/6.8.0/bin/mono : altstack_handle_and_restore
2020-05-04T23:42:49.9892500Z 	0x110b39d74 - /Users/runner/.nuget/packages/resizetizer.nt/0.1.0-preview8/build/libSkiaSharp.dylib : gr_backendrendertarget_get_gl_framebufferinfo
2020-05-04T23:42:49.9893580Z 	0x110a085aa - /Users/runner/.nuget/packages/resizetizer.nt/0.1.0-preview8/build/libSkiaSharp.dylib : sk_typeface_get_family_name
2020-05-04T23:42:49.9894330Z 	0x10e3996fb - Unknown
2020-05-04T23:42:49.9894500Z 
2020-05-04T23:42:49.9894750Z =================================================================
2020-05-04T23:42:49.9895060Z   svg.FromSvgDocument took 67ms
2020-05-04T23:42:49.9895290Z 	Telemetry Dumper:
2020-05-04T23:42:49.9895580Z =================================================================
2020-05-04T23:42:49.9908350Z Pkilling 0x700004cee000 from 0x7000054fa000
2020-05-04T23:42:49.9922550Z Pkilling 0x700004aa8000 from 0x7000054fa000
2020-05-04T23:42:49.9936850Z Pkilling 0x70000459c000 from 0x7000054fa000
2020-05-04T23:42:49.9937630Z Pkilling 0x7000048a5000 from 0x7000054fa000
2020-05-04T23:42:49.9938210Z Pkilling 0x700005d06000 from 0x7000054fa000
2020-05-04T23:42:49.9938770Z Pkilling 0x10beb0dc0 from 0x7000054fa000
2020-05-04T23:42:49.9939270Z Pkilling 0x700005b03000 from 0x7000054fa000
2020-05-04T23:42:49.9939810Z Pkilling 0x700005900000 from 0x7000054fa000
2020-05-04T23:42:49.9940310Z Pkilling 0x7000056fd000 from 0x7000054fa000
2020-05-04T23:42:49.9940840Z Pkilling 0x7000052f7000 from 0x7000054fa000
2020-05-04T23:42:49.9941350Z Pkilling 0x7000050f4000 from 0x7000054fa000
2020-05-04T23:42:49.9941690Z Pkilling 0x700004ef1000 from 0x7000054fa000
2020-05-04T23:42:49.9942000Z Pkilling 0x700004cab000 from 0x7000054fa000
2020-05-04T23:42:50.0006210Z Entering thread summarizer pause from 0x7000054fa000
2020-05-04T23:42:50.0024590Z Finished thread summarizer pause from 0x7000054fa000.
2020-05-04T23:42:50.0300230Z 
2020-05-04T23:42:50.0300760Z Waiting for dumping threads to resume
2020-05-04T23:42:50.0822980Z   Save Image took 93ms
2020-05-04T23:42:50.0850920Z   Save Image took 2ms
2020-05-04T23:42:50.0892590Z   Save Image took 3ms
2020-05-04T23:42:50.0970030Z   Save Image took 7ms
2020-05-04T23:42:50.1097370Z   Save Image took 12ms
2020-05-04T23:42:50.1165990Z   Open SVG took 6ms
2020-05-04T23:42:50.1166270Z   new SKSvg() took 0ms
2020-05-04T23:42:50.1196500Z   svg.FromSvgDocument took 3ms
2020-05-04T23:42:50.1212600Z   Save Image took 1ms
2020-05-04T23:42:50.1238160Z   Save Image took 2ms
2020-05-04T23:42:50.1276150Z   Save Image took 3ms
2020-05-04T23:42:50.1348010Z   Save Image took 6ms
2020-05-04T23:42:50.1463720Z   Save Image took 11ms
2020-05-04T23:42:51.0659830Z 
2020-05-04T23:42:51.0660470Z =================================================================
2020-05-04T23:42:51.0660790Z 	External Debugger Dump:
2020-05-04T23:42:51.0661120Z =================================================================
2020-05-04T23:42:51.0669880Z 
2020-05-04T23:42:51.0670410Z =================================================================
2020-05-04T23:42:51.0670740Z 	Basic Fault Address Reporting
2020-05-04T23:42:51.0671060Z =================================================================
2020-05-04T23:42:51.0671930Z Memory around native instruction pointer (0x110b39d74):0x110b39d64  48 8b 07 5d ff a0 90 00 00 00 66 90 55 48 89 e5  H..]......f.UH..
2020-05-04T23:42:51.0672500Z 0x110b39d74  48 8b 07 48 8b 80 88 00 00 00 5d ff e0 66 2e 0f  H..H......]..f..
2020-05-04T23:42:51.0672930Z 0x110b39d84  1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 89 e5  .........D..UH..
2020-05-04T23:42:51.0673340Z 0x110b39d94  53 50 48 89 f3 48 8b 07 ff 50 70 85 c0 74 0f 48  SPH..H...Pp..t.H
2020-05-04T23:42:51.0673590Z 
2020-05-04T23:42:51.0674120Z =================================================================
2020-05-04T23:42:51.0674660Z 	Managed Stacktrace:
2020-05-04T23:42:51.0674970Z =================================================================
2020-05-04T23:42:51.0675300Z 	  at <unknown> <0xffffffff>
2020-05-04T23:42:51.0676090Z 	  at SkiaSharp.SkiaApi:sk_typeface_get_family_name <0x000aa>
2020-05-04T23:42:51.0676510Z 	  at SkiaSharp.SKTypeface:get_FamilyName <0x0004a>
2020-05-04T23:42:51.0676890Z 	  at Svg.Skia.DefaultTypefaceProvider:FromFamilyName <0x0030a>
2020-05-04T23:42:51.0677270Z 	  at Svg.Skia.SvgTextExtensions:SetTypeface <0x0018c>
2020-05-04T23:42:51.0677640Z 	  at Svg.Skia.SvgTextExtensions:SetSKPaintText <0x00332>
2020-05-04T23:42:51.0679200Z 	  at Svg.Skia.TextDrawable:DrawTextBase <0x0059a>
2020-05-04T23:42:51.0679600Z 	  at Svg.Skia.TextDrawable:DrawTextSpan <0x00202>
2020-05-04T23:42:51.0679940Z 	  at Svg.Skia.TextDrawable:DrawText <0x00902>
2020-05-04T23:42:51.0680260Z 	  at Svg.Skia.TextDrawable:Draw <0x000a2>
2020-05-04T23:42:51.0680590Z 	  at Svg.Skia.DrawableContainer:OnDraw <0x0010c>
2020-05-04T23:42:51.0680890Z 	  at Svg.Skia.Drawable:Draw <0x003f8>
2020-05-04T23:42:51.0681260Z 	  at Svg.Skia.DrawableContainer:OnDraw <0x0010c>
2020-05-04T23:42:51.0681570Z 	  at Svg.Skia.Drawable:Draw <0x003f8>
2020-05-04T23:42:51.0681870Z 	  at Svg.Skia.Drawable:OnDraw <0x0004c>
2020-05-04T23:42:51.0682180Z 	  at SkiaSharp.SKDrawable:DrawInternal <0x001d9>
2020-05-04T23:42:51.0682520Z 	  at SkiaSharp.SKDrawable:DrawInternal <0x0007a>
2020-05-04T23:42:51.0682890Z 	  at <unknown> <0xffffffff>
2020-05-04T23:42:51.0683190Z 	  at SkiaSharp.SkiaApi:sk_drawable_draw <0x000b8>
2020-05-04T23:42:51.0683510Z 	  at SkiaSharp.SKDrawable:Draw <0x00072>
2020-05-04T23:42:51.0683820Z 	  at SkiaSharp.SKDrawable:Draw <0x000c2>
2020-05-04T23:42:51.0684120Z 	  at Svg.Skia.SKSvg:ToPicture <0x00232>
2020-05-04T23:42:51.0684430Z 	  at Svg.Skia.SKSvg:FromSvgDocument <0x00062>
2020-05-04T23:42:51.0684760Z 	  at Resizetizer.SkiaSharpSvgTools:.ctor <0x00572>
2020-05-04T23:42:51.0685090Z 	  at Resizetizer.Resizer:Resize <0x00162>
2020-05-04T23:42:51.0685420Z 	  at <>c__DisplayClass25_0:<DoExecute>b__0 <0x00192>
2020-05-04T23:42:51.0685780Z 	  at <>c__DisplayClass33_0`2:<ForEachWorker>b__0 <0x0006f>
2020-05-04T23:42:51.0686140Z 	  at <>c__DisplayClass19_0`1:<ForWorker>b__1 <0x00356>
2020-05-04T23:42:51.0686460Z 	  at Replica`1:ExecuteAction <0x00057>
2020-05-04T23:42:51.0686730Z 	  at Replica:Execute <0x0007b>
2020-05-04T23:42:51.0687000Z 	  at <>c:<Execute>b__7_0 <0x00059>
2020-05-04T23:42:51.0687320Z 	  at System.Threading.Tasks.Task:InnerInvoke <0x0008f>
2020-05-04T23:42:51.0687920Z 	  at System.Threading.Tasks.Task:Execute <0x00037>
2020-05-04T23:42:51.0688310Z 	  at System.Threading.Tasks.Task:ExecutionContextCallback <0x0005b>
2020-05-04T23:42:51.0688700Z 	  at System.Threading.ExecutionContext:RunInternal <0x001a9>
2020-05-04T23:42:51.0689070Z 	  at System.Threading.ExecutionContext:Run <0x00042>
2020-05-04T23:42:51.0689450Z 	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x000f6>
2020-05-04T23:42:51.0689830Z 	  at System.Threading.Tasks.Task:ExecuteEntry <0x000e8>
2020-05-04T23:42:51.0690260Z 	  at System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem <0x00026>
2020-05-04T23:42:51.0690710Z 	  at System.Threading.ThreadPoolWorkQueue:Dispatch <0x00279>
2020-05-04T23:42:51.0691110Z 	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x0001c>
2020-05-04T23:42:51.0691490Z 	  at <Module>:runtime_invoke_bool <0x000a5>
2020-05-04T23:42:51.0691980Z =================================================================
```

**Comment by Redth** [comment] 2020-09-16 17:33
Duplicate of #8

**Closed by Redth** 2020-09-16 17:33 UTC

**Comment by Piyali123** [comment] 2021-03-02 06:53
Getting build error in Azure Devops pipeline using ResizetizerNT(resizetizer.nt 0.2.0) in Xamarin.Android project.

PFB log details-


2021-03-02T04:40:33.8764351Z   Compiling Xaml, assembly: obj\Debug\netstandard2.0\OT.dll
2021-03-02T04:40:44.4794755Z   Creating "obj\Debug\netstandard2.0\XamlC.stamp" because "AlwaysCreate" was specified.
2021-03-02T04:40:44.5470152Z _CopyAppConfigFile:
2021-03-02T04:40:44.5471132Z   Copying file from "D:\a\1\s\src\OTobj\Debug\netstandard2.0\OT.csproj.App.config" to "D:\a\1\b\Debug\OT.dll.config".
2021-03-02T04:40:45.2160675Z CopyFilesToOutputDirectory:
2021-03-02T04:40:45.2162628Z   Copying file from "D:\a\1\s\src\OT\obj\Debug\netstandard2.0\OT.dll" to "D:\a\1\b\Debug\OT.dll".
2021-03-02T04:40:45.2375473Z   OT -> D:\a\1\b\Debug\OT.dll
2021-03-02T04:40:45.2379126Z   Copying file from "D:\a\1\s\src\OT\OT\obj\Debug\netstandard2.0\OT.pdb" to "D:\a\1\b\Debug\OT.pdb".
2021-03-02T04:40:45.2901337Z Done Building Project "D:\a\1\s\src\OT.csproj" (default targets).
**2021-03-02T04:40:46.0659453Z ##[error]src\OT\packages\Resizetizer.NT.0.2.0\build\Resizetizer.NT.targets(155,3): Error : One or more errors occurred.
2021-03-02T04:40:46.0674374Z D:\a\1\s\src\OT\packages\Resizetizer.NT.0.2.0\build\Resizetizer.NT.targets(155,3): error : One or more errors occurred. [D:\a\1\s\src\OT\Droid\OT.Droid.csproj]
2021-03-02T04:40:46.0780880Z Done Building Project "D:\a\1\s\src\OT\Droid\OT.Droid.csproj" (PackageForAndroid target(s)) -- FAILED.**
2021-03-02T04:40:46.0875568Z 
2021-03-02T04:40:46.0876318Z Build FAILED.

**Build is running fine with Xamarin.iOS task.**
